// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: availability.sql

package db

import (
	"context"
)

const deleteAvailability = `-- name: DeleteAvailability :exec
DELETE FROM dispos
WHERE user_id = $1
  AND day_index = $2
  AND slot_index = $3
  AND week = $4
`

type DeleteAvailabilityParams struct {
	UserID    string `json:"user_id"`
	DayIndex  int16  `json:"day_index"`
	SlotIndex int16  `json:"slot_index"`
	Week      string `json:"week"`
}

func (q *Queries) DeleteAvailability(ctx context.Context, arg DeleteAvailabilityParams) error {
	_, err := q.db.Exec(ctx, deleteAvailability,
		arg.UserID,
		arg.DayIndex,
		arg.SlotIndex,
		arg.Week,
	)
	return err
}

const getAvailabilityCounts = `-- name: GetAvailabilityCounts :many
SELECT day_index, slot_index, COUNT(*) AS count
FROM dispos
WHERE week = $1
GROUP BY day_index, slot_index
ORDER BY day_index, slot_index
`

type GetAvailabilityCountsRow struct {
	DayIndex  int16 `json:"day_index"`
	SlotIndex int16 `json:"slot_index"`
	Count     int64 `json:"count"`
}

func (q *Queries) GetAvailabilityCounts(ctx context.Context, week string) ([]GetAvailabilityCountsRow, error) {
	rows, err := q.db.Query(ctx, getAvailabilityCounts, week)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAvailabilityCountsRow
	for rows.Next() {
		var i GetAvailabilityCountsRow
		if err := rows.Scan(&i.DayIndex, &i.SlotIndex, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailabilityUsers = `-- name: GetAvailabilityUsers :many
SELECT day_index, slot_index, user_id
FROM dispos
WHERE week = $1
ORDER BY day_index, slot_index, user_id
`

type GetAvailabilityUsersRow struct {
	DayIndex  int16  `json:"day_index"`
	SlotIndex int16  `json:"slot_index"`
	UserID    string `json:"user_id"`
}

func (q *Queries) GetAvailabilityUsers(ctx context.Context, week string) ([]GetAvailabilityUsersRow, error) {
	rows, err := q.db.Query(ctx, getAvailabilityUsers, week)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAvailabilityUsersRow
	for rows.Next() {
		var i GetAvailabilityUsersRow
		if err := rows.Scan(&i.DayIndex, &i.SlotIndex, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSondageMessageByWeek = `-- name: GetSondageMessageByWeek :one
SELECT week, message_id
FROM sondage_messages
WHERE week = $1
`

func (q *Queries) GetSondageMessageByWeek(ctx context.Context, week string) (SondageMessage, error) {
	row := q.db.QueryRow(ctx, getSondageMessageByWeek, week)
	var i SondageMessage
	err := row.Scan(&i.Week, &i.MessageID)
	return i, err
}

const getUserAvailability = `-- name: GetUserAvailability :many
SELECT day_index, slot_index
FROM dispos
WHERE week = $1
  AND user_id = $2
ORDER BY day_index, slot_index
`

type GetUserAvailabilityParams struct {
	Week   string `json:"week"`
	UserID string `json:"user_id"`
}

type GetUserAvailabilityRow struct {
	DayIndex  int16 `json:"day_index"`
	SlotIndex int16 `json:"slot_index"`
}

func (q *Queries) GetUserAvailability(ctx context.Context, arg GetUserAvailabilityParams) ([]GetUserAvailabilityRow, error) {
	rows, err := q.db.Query(ctx, getUserAvailability, arg.Week, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserAvailabilityRow
	for rows.Next() {
		var i GetUserAvailabilityRow
		if err := rows.Scan(&i.DayIndex, &i.SlotIndex); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAvailability = `-- name: InsertAvailability :exec
INSERT INTO dispos (user_id, day_index, slot_index, week)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, day_index, slot_index, week) DO NOTHING
`

type InsertAvailabilityParams struct {
	UserID    string `json:"user_id"`
	DayIndex  int16  `json:"day_index"`
	SlotIndex int16  `json:"slot_index"`
	Week      string `json:"week"`
}

func (q *Queries) InsertAvailability(ctx context.Context, arg InsertAvailabilityParams) error {
	_, err := q.db.Exec(ctx, insertAvailability,
		arg.UserID,
		arg.DayIndex,
		arg.SlotIndex,
		arg.Week,
	)
	return err
}

const listSondageMessageIDs = `-- name: ListSondageMessageIDs :many
SELECT message_id FROM sondage_messages
`

func (q *Queries) ListSondageMessageIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listSondageMessageIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var message_id string
		if err := rows.Scan(&message_id); err != nil {
			return nil, err
		}
		items = append(items, message_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSondageMessage = `-- name: UpsertSondageMessage :exec
INSERT INTO sondage_messages (week, message_id)
VALUES ($1, $2)
ON CONFLICT (week) DO UPDATE
SET message_id = EXCLUDED.message_id
`

type UpsertSondageMessageParams struct {
	Week      string `json:"week"`
	MessageID string `json:"message_id"`
}

func (q *Queries) UpsertSondageMessage(ctx context.Context, arg UpsertSondageMessageParams) error {
	_, err := q.db.Exec(ctx, upsertSondageMessage, arg.Week, arg.MessageID)
	return err
}
