// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guild_config.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGuildConfig = `-- name: GetGuildConfig :one
SELECT guild_id, channel_id, role_id
FROM guild_config
WHERE guild_id = $1
`

func (q *Queries) GetGuildConfig(ctx context.Context, guildID string) (GuildConfig, error) {
	row := q.db.QueryRow(ctx, getGuildConfig, guildID)
	var i GuildConfig
	err := row.Scan(&i.GuildID, &i.ChannelID, &i.RoleID)
	return i, err
}

const setGuildConfigChannel = `-- name: SetGuildConfigChannel :exec
INSERT INTO guild_config (guild_id, channel_id)
VALUES ($1, $2)
ON CONFLICT (guild_id) DO UPDATE
SET channel_id = EXCLUDED.channel_id
`

type SetGuildConfigChannelParams struct {
	GuildID   string      `json:"guild_id"`
	ChannelID pgtype.Text `json:"channel_id"`
}

func (q *Queries) SetGuildConfigChannel(ctx context.Context, arg SetGuildConfigChannelParams) error {
	_, err := q.db.Exec(ctx, setGuildConfigChannel, arg.GuildID, arg.ChannelID)
	return err
}

const setGuildConfigRole = `-- name: SetGuildConfigRole :exec
INSERT INTO guild_config (guild_id, role_id)
VALUES ($1, $2)
ON CONFLICT (guild_id) DO UPDATE
SET role_id = EXCLUDED.role_id
`

type SetGuildConfigRoleParams struct {
	GuildID string      `json:"guild_id"`
	RoleID  pgtype.Text `json:"role_id"`
}

func (q *Queries) SetGuildConfigRole(ctx context.Context, arg SetGuildConfigRoleParams) error {
	_, err := q.db.Exec(ctx, setGuildConfigRole, arg.GuildID, arg.RoleID)
	return err
}
