// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Dispo struct {
	UserID    string             `json:"user_id"`
	DayIndex  int16              `json:"day_index"`
	SlotIndex int16              `json:"slot_index"`
	Week      string             `json:"week"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GuildConfig struct {
	GuildID   string      `json:"guild_id"`
	ChannelID pgtype.Text `json:"channel_id"`
	RoleID    pgtype.Text `json:"role_id"`
}

type SondageMessage struct {
	Week      string `json:"week"`
	MessageID string `json:"message_id"`
}
